apiVersion: v1
kind: ConfigMap
metadata:
  name: isaelfatama-api-config
  namespace: isaelfatama-api-ns
  labels:
    app: isaelfatama-api

data:
  APP_ENV: "produccion"
  APP_PORT: "8085"
  APP_VERSION: "1.0.0"